package org.anon.gui.pdf;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Date;

import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.Paragraph;

public class CustomPdfProcessor {
	
	private static Font headerFont = new Font(Font.TIMES_ROMAN, 18, Font.BOLD);
	private static Font smallBold = new Font(Font.TIMES_ROMAN, 12, Font.BOLD);
	
	public void preProcessPDF(Object document) throws DocumentException, MalformedURLException, IOException {
		
		Document pdf = (Document) document;
		pdf.open();
		
		ServletContext servletContext = (ServletContext) FacesContext.getCurrentInstance().getExternalContext().getContext();
		String logo = servletContext.getRealPath("") + File.separator + "resources" 
        		+ File.separator + "images" + File.separator + "anonimecsOrig.png";
		
		Image image = Image.getInstance(logo);
		image.scaleAbsolute(50, 50);
		image.setAlignment(Element.ALIGN_RIGHT);
		
		Paragraph preface = new Paragraph();
		preface.add(image);
		addEmptyLine(preface, 1);
		preface.add(new Paragraph("Method Report", headerFont));           
		addEmptyLine(preface, 1);
		preface.add(new Paragraph("Report generated by: " + "username" + ", " + new Date(), smallBold));
		addEmptyLine(preface, 3);
		
		pdf.add(preface);
	}
	
	private static void addEmptyLine(Paragraph paragraph, int number) {
	    for (int i = 0; i < number; i++) {
	      paragraph.add(new Paragraph(" "));
	    }
	}

}
